### ISSUE TITLE
Blurred label

### ISSUE THREAD

**Issue by jschneiderPatinfo** [robcrocombe/chartjs-plugin-outerLabels#1]
Hi,

Do you know why the labels are blurred when printed?

![image](https://user-images.githubusercontent.com/25950371/69323450-08ea3700-0c47-11ea-8688-f4d6a93a935f.png)

Is there a way to correct this ?

**Comment by robcrocombe** [comment]
Hey @jschneiderPatinfo! Are you using a high-DPI/retina screen? Looks like an issue with that as it affects the pie chart too. Check out the [Chart.js docs](https://www.chartjs.org/docs/latest/general/device-pixel-ratio.html).
